name: keymap
description: A reusable keyboard shortcuts widget with a flexible, minimal UI and focus handling.
version: 0.0.90
homepage: https://github.com/pmutisya/keymap

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_markdown: ^0.6.10+2
  flutter:
    sdk: flutter
  zarainia_utils:
    git: https://github.com/Zarainia/zarainia-utils-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
